# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
- repo: git://github.com/timothycrosley/isort
  rev: 5.9.3
  hooks:
    - id: isort
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
    - id: mypy
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-merge-conflict
    - id: no-commit-to-branch
      args: [--branch, main]
    - id: flake8
      entry: pflake8
      additional_dependencies: [flake8-docstrings, pep8-naming, pyproject-flake8]
    - id: check-json
    - id: check-yaml